# frozen_string_literal: true

module Exports
  class ClassReportPdf < BaseExport
    def suggested_filename
      "class-report-#{Date.current.iso8601}.pdf"
    end

    def build_io
      require "prawn"
      require "prawn/table"
      range = date_range
      scope = TrainingClass.where(date: range)
      scope = scope.where(id: filters[:course_id]) if filters[:course_id].present?
      classes = scope.order(:date).includes(:attendees)

      io = StringIO.new
      Prawn::Document.new(page_size: "A4", margin: 36) do |pdf|
        Exports::PrawnFontHelper.apply_font(pdf)
        header(pdf)
        pdf.move_down 20
        pdf.text "Class Report", size: 16, style: :bold
        pdf.text "Period: #{range.begin} to #{range.end}", size: 10
        pdf.move_down 16

        classes.each do |tc|
          pdf.text tc.title, size: 12, style: :bold
          pdf.text "Date: #{tc.date}  |  Location: #{tc.location}", size: 9
          pdf.move_down 6
          atts = tc.attendees.attendees
          if include_sections[:attendee_list] && atts.any?
            rows = [["Name", "Email", "Seats", "Payment", "Total"]] + atts.limit(50).map { |a| [a.name, a.email, a.seats.to_s, a.payment_status.to_s, "฿#{a.total_final_price.round(2)}"] }
            pdf.table(rows, width: pdf.bounds.width, row_colors: %w[e8e8e8 ffffff])
          else
            pdf.text "Attendees: #{atts.count} (#{atts.sum(:seats)} seats)", size: 10
          end
          pdf.move_down 14
        end

        footer(pdf)
      end.render(io)
      io.rewind
      io
    end

    private

    def header(pdf)
      company = Exports::PrawnFontHelper.company_for_prawn
      pdf.text company[:name], size: 12, style: :bold
      pdf.text company[:address], size: 9
      pdf.stroke_horizontal_rule
    end

    def footer(pdf)
      pdf.number_pages "Generated by ODT Admin System • Confidential • Page <page> of <total>", at: [pdf.bounds.left, 0], width: pdf.bounds.width, align: :center, size: 8
    end
  end
end
