# frozen_string_literal: true

module Exports
  class CustomerSummaryPdf < BaseExport
    def suggested_filename
      "customer-summary-#{Date.current.iso8601}.pdf"
    end

    def build_io
      require "prawn"
      require "prawn/table"
      customers = Customer.order(:name).limit(500)

      io = StringIO.new
      Prawn::Document.new(page_size: "A4", margin: 36) do |pdf|
        Exports::PrawnFontHelper.apply_font(pdf)
        company = Exports::PrawnFontHelper.company_for_prawn
        pdf.text company[:name], size: 12, style: :bold
        pdf.text company[:address], size: 9
        pdf.stroke_horizontal_rule
        pdf.move_down 16
        pdf.text "Customer Summary", size: 16, style: :bold
        pdf.move_down 12
        rows = [["Name", "Email", "Company", "Tax ID"]] + customers.map { |c| [c.name, c.email, c.company.to_s, c.tax_id.to_s] }
        pdf.table(rows, width: pdf.bounds.width, row_colors: %w[e8e8e8 ffffff])
        pdf.number_pages "Generated by ODT Admin System • Page <page> of <total>", at: [pdf.bounds.left, 0], width: pdf.bounds.width, align: :center, size: 8
      end.render(io)
      io.rewind
      io
    end
  end
end
