# frozen_string_literal: true

module Exports
  class FinancialReportPdf < BaseExport
    def suggested_filename
      "financial-report-#{Date.current.iso8601}.pdf"
    end

    def build_io
      require "prawn"
      require "prawn/table"
      range = date_range
      attendees = scope_attendees.includes(:training_class, :promotions)

      gross = attendees.sum(&:gross_sales_amount)
      total_discount = attendees.sum { |a| a.total_discount_amount * (a.seats || 1) }
      net_before_vat = attendees.sum(&:total_price_before_vat)
      vat = attendees.sum(&:total_vat_amount)
      total_incl = attendees.sum(&:total_final_price)
      cash = attendees.where(payment_status: "Paid").sum(&:total_final_price)
      outstanding = attendees.where(payment_status: "Pending").sum(&:total_final_price)

      io = StringIO.new
      Prawn::Document.new(page_size: "A4", margin: 36) do |pdf|
        Exports::PrawnFontHelper.apply_font(pdf)
        header(pdf)
        pdf.move_down 20
        pdf.text "Financial Report", size: 16, style: :bold
        pdf.text "Period: #{range.begin} to #{range.end}", size: 10
        pdf.move_down 16

        # Executive summary
        pdf.text "Executive Summary", size: 12, style: :bold
        pdf.move_down 6
        data = [
          ["Gross Sales", "฿#{number_with_delimiter(gross.round(2))}"],
          ["Total Discounts", "฿#{number_with_delimiter(total_discount.round(2))}"],
          ["Net (Before VAT)", "฿#{number_with_delimiter(net_before_vat.round(2))}"],
          ["VAT 7%", "฿#{number_with_delimiter(vat.round(2))}"],
          ["Total (Incl. VAT)", "฿#{number_with_delimiter(total_incl.round(2))}"],
          ["Cash Received", "฿#{number_with_delimiter(cash.round(2))}"],
          ["Outstanding", "฿#{number_with_delimiter(outstanding.round(2))}"]
        ]
        pdf.table(data, header: true, row_colors: %w[f8f8f8 ffffff], width: pdf.bounds.width)

        if include_sections[:promotion_breakdown]
          pdf.move_down 20
          pdf.text "Revenue by Promotion", size: 12, style: :bold
          pdf.move_down 6
          by_promo = attendees.group_by { |a| a.promotions.where(active: true).pluck(:name).join(", ") }.transform_values { |list| list.sum(&:total_final_price) }
          promo_rows = by_promo.map { |name, amt| [name.presence || "No promo", "฿#{number_with_delimiter(amt.round(2))}"] }
          pdf.table(promo_rows, width: pdf.bounds.width) if promo_rows.any?
        end

        footer(pdf)
      end.render(io)
      io.rewind
      io
    end

    private

    def header(pdf)
      company = Exports::PrawnFontHelper.company_for_prawn
      pdf.text company[:name], size: 12, style: :bold
      pdf.text company[:address], size: 9
      pdf.text "Email: #{company[:email]}  |  Phone: #{company[:phone]}  |  Tax ID: #{company[:tax_id]}", size: 8
      pdf.stroke_horizontal_rule
    end

    def footer(pdf)
      pdf.number_pages "Generated by ODT Admin System • Confidential • Page <page> of <total>", at: [pdf.bounds.left, 0], width: pdf.bounds.width, align: :center, size: 8
    end

    def number_with_delimiter(n)
      n.to_s.reverse.gsub(/(\d{3})(?=\d)/, '\\1,').reverse
    end
  end
end
